export const SURPRISE_ME_PROMPTS = [
  "I ate an entire pizza by myself and now I feel sick.",
  "I tripped on the sidewalk but pretended I was just jogging.",
  "I accidentally waved at someone who was waving at the person behind me.",
  "I spent 45 minutes trying to find a movie on Netflix and then just went to sleep.",
  "My dog threw up on the carpet this morning.",
  "I replied 'you too' when the waiter told me to enjoy my meal.",
  "I bought a gym membership 3 months ago and haven't gone once.",
  "I got fired today because I told my boss his ideas were bad.",
  "I slept through my alarm and missed my morning standup.",
  "I aggressively typed on my keyboard so my coworkers thought I was busy.",
  "I hid in the bathroom for 20 minutes to avoid a team-building exercise.",
  "I bought a $7 iced coffee and immediately dropped it in the parking lot.",
  "I sent a professional email with a typo in the very first word.",
  "I scrolled TikTok for 3 hours when I was supposed to be working.",
  "I accidentally liked my ex's Instagram picture from 2018.",
  "I wore the same sweatpants for four days in a row.",
  "I made eye contact with a stranger on the train and then stared at my phone for the rest of the ride.",
  "I killed my succulent by watering it exactly one time.",
  "I spent $150 on aesthetic organization bins and my room is still a mess.",
  "I bought a planner in January and haven't opened it since February.",
  "I confidently walked into the wrong meeting room and just sat down.",
  "I forgot to mute my microphone while eating chips on a zoom call.",
  "I hit 'reply all' to tell the whole company I would like a turkey sandwich.",
  "I lied about seeing a movie so I wouldn't have to talk about it.",
  "I spent half my paycheck on clothes I'll never actually wear outside.",
  "I got a haircut and cried in my car afterwards.",
  "I ordered takeout because the dishes in the sink were too intimidating.",
  "I faked a wifi outage to get out of a Zoom meeting.",
  "I drank three energy drinks and still took a nap.",
  "I bought fresh vegetables and watched them slowly rot in the fridge.",
  "I stared blindly at my screen for an hour hoping code would write itself.",
  "I put on workout clothes just to sit on the couch and watch TV.",
  "I said 'sounds good' to a question I didn't actually hear.",
  "I pushed a pull door in front of a group of teenagers.",
  "I aggressively pressed the elevator button even though it was already lit.",
  "I accidentally called my teacher 'Mom'.",
  "I started a diet at 9 AM and ate a donut at 11 AM.",
  "I gave a fake name at Starbucks and then forgot it when they called my order.",
  "I created a 'to-do' list just so I could cross off things I already did.",
  "I practiced an argument in the shower and lost.",
  "I checked my fridge, lowered my standards, and ate a slice of plain bread.",
  "I read a single page of a book and then rewarded myself with 3 hours of scrolling.",
  "I brought a reusable bag to the grocery store and left it in my car.",
  "I laughed at a joke I didn't understand and just hoped it wasn't a question.",
  "I checked the tracking on my package 12 times in one day.",
  "I bought a bunch of bananas and threw them away a week later.",
  "I took a 15-minute break that turned into a 3-hour spiral.",
  "I nodded enthusiastically during a presentation while thinking about lunch.",
  "I tried to catch a falling pen and accidentally slapped my coworker.",
  "I complained about being broke while holding an $8 coffee.",
  "I hit the snooze button so many times I actually broke my phone.",
  "I spent 20 minutes trying to remember a password instead of clicking 'forgot password'.",
  "I accidentally sent a heart emoji to my landlord.",
  "I started a hobby, bought all the expensive gear, and gave up 2 days later.",
  "I put my headphones in without playing music just so people wouldn't talk to me.",
  "I tripped up the stairs and tried to make it look like a new dance move.",
  "I bought a standing desk and have never stood at it once.",
  "I promised myself I'd go to sleep early and then stayed up till 3 AM watching conspiracy videos.",
  "I tried to use a coupon that expired in 2019.",
  "I got mad at my GPS for taking me the exact way I asked it to.",
  "I wore sunglasses inside because I was too lazy to do my makeup.",
  "I bought a book to make myself look smart and haven't opened it.",
  "I spent an hour looking for my phone while I was holding it.",
  "I confidently gave wrong directions to a tourist.",
  "I ate a family-size bag of chips while reading an article on health.",
  "I told a story halfway through, realized it wasn't funny, and just stopped.",
  "I accidentally spit on my screen while laughing at a meme.",
  "I bought expensive skin care products and still don't wash my face at night.",
  "I complained about being tired after doing absolutely nothing all day.",
  "I took 40 selfies to post one picture where I look like I don't care.",
  "I ignored a phone call and immediately texted back 'what's up?'.",
  "I bought a water bottle to stay hydrated and drank two sips all day.",
  "I held the door for someone who was too far away, forcing them into a light jog.",
  "I left my laundry in the dryer for a week and just picked clothes out of it.",
  "I tried a new recipe and ended up ordering a pizza.",
  "I signed up for a free trial and forgot to cancel it for 6 months.",
  "I got scared by my own reflection in a dark window.",
  "I bought a cute notebook and am too afraid to ruin it by actually writing in it.",
  "I argued with someone on the internet for 2 hours.",
  "I dropped my keys while trying to unlock the door with my hands full.",
  "I confidently walked in the wrong direction and had to pretend I forgot something to turn around.",
  "I spent 10 minutes untangling headphones only to realize I brought the broken pair.",
  "I bought a new plant and immediately apologized to it for its inevitable death.",
  "I checked my bank account through one eye so it wouldn't hurt as much.",
  "I laughed out loud in a completely silent room.",
  "I tried to discreetly unstick my shirt from my back and failed.",
  "I bought a fancy coffee maker and still go to the drive-thru every morning.",
  "I wore a shirt inside out all day and nobody told me.",
  "I got reasonably upset when the microwave beeped loudly at 2 AM.",
  "I spent 30 minutes looking for the remote before realizing I was sitting on it.",
  "I bought a new outfit and refused to wear it until a 'special occasion'.",
  "I tried to wink at someone and ended up blinking both eyes really hard.",
  "I confidently sang the wrong lyrics to a song out loud.",
  "I bought a bunch of healthy snacks and ate the single chocolate bar instead.",
  "I spent an hour curating a playlist for a 10-minute drive.",
  "I tried to take a cute candid picture and ended up with a double chin.",
  "I got overly attached to a fictional character and cried when the show ended.",
  "I bought a new phone case and immediately dropped my phone on its screen.",
  "I spent an entire weekend doing nothing and complained about how fast it went.",
  "I tried to do a DIY project and ended up gluing my fingers together.",
  "I refreshed my email inbox 5 times even though I have zero unread messages."
];
